### **Calculating norms of vectors.**

In [ ]:
import numpy as np
#||u||_2, Euclidean norm, default
u = np.array([-1, -9,2])
norm = np.linalg.norm(u)
print("The Euclidean norm is:",norm)
#||u||_1, 1-norm
norm = np.linalg.norm(u, ord=1)
print("The 1-norm is:",norm)
#||u||_inf, inf-norm
norm = np.linalg.norm(u, ord=np.inf)
print("The inf-norm is:",norm)

The Euclidean norm is: 9.273618495495704
The 1-norm is: 12.0
The inf-norm is: 9.0


### **Relative Residual**

In [ ]:
#Jacobi
A = np.array([[5.,-1,2],[-1,4,1],[1,6,-7]])
print("A= ",A)
b = np.array([[1.,-2.,5.]]).T
print("b= ",b)
x_12 = np.array([[.4838,-.1795,-.7998]]).T
print("x_12= ",x_12)
relative_residual = np.linalg.norm(b-np.dot(A,x_12))/np.linalg.norm(b)
print(relative_residual)

A=  [[ 5. -1.  2.]
 [-1.  4.  1.]
 [ 1.  6. -7.]]
b=  [[ 1.]
 [-2.]
 [ 5.]]
x_12=  [[ 0.4838]
 [-0.1795]
 [-0.7998]]
0.0010476958846280654


In [ ]:
#GS
A = np.array([[5.,-1,2],[-1,4,1],[1,6,-7]])
print("A = ",A)
b = np.array([[1.,-2.,5.]]).T
print("b= ",b)
x_12 = np.array([[.4837,-.1794,-.7989]]).T
print(x_12)
relative_residual = np.linalg.norm(b-np.dot(A,x_12))/np.linalg.norm(b)
print(relative_residual)

A =  [[ 5. -1.  2.]
 [-1.  4.  1.]
 [ 1.  6. -7.]]
b=  [[ 1.]
 [-2.]
 [ 5.]]
[[ 0.4837]
 [-0.1794]
 [-0.7989]]
8.366600265339834e-05


### **Matrix Norms**

In [ ]:
import numpy as np
A = np.array([[1.,13.,5.,-9], [12., 55.,5.,-6],[18.,90.,1.,-1],[3.,0.,2.,3]])
# L1 norm
l1_norm = np.linalg.norm(A, ord=1)
print("L1 norm A:", l1_norm)

# L2 norm
l2_norm = np.linalg.norm(A, ord=2)
print("L2 norm A:", l2_norm)

# Infinity norm
infinity_norm = np.linalg.norm(A, ord=np.inf)
print("Infinity norm A:", infinity_norm)

L1 norm A: 158.0
L2 norm A: 108.63728683252275
Infinity norm A: 110.0


### **Code and Example to run the Jacobi Method**

In [ ]:
# Jacobi method
def jacobi(A, b, x_0, k):
    """
    Perform k steps of Jacobi method
    A: the matrix
    b: the right-hand-side
    x_0: initial guess x0
    k: number of steps
    """
    d = np.diag(A)
    r  = A-np.diag(d)
    # Initialize the solution vector
    x = x_0.copy()
    for j in range(k):
        x = (b-np.dot(r,x))/d
        print(np.linalg.norm(b-np.dot(A,x))/np.linalg.norm(b))
    return x
#https://yaningliucudenver.github.io/Numerical-Analysis-I/bookchapter3-2.html

In [ ]:
import numpy as np
# output for Jacobi
A = np.array([[3.,-2,0],[-2,4,-1],[0,1,2]],dtype=float)
b = np.array([1,2.,-2])
x0 = np.array([1.,1.,1.])
#compute and print out the 1,2, and infinity norm of B_J
D = np.array([[3.,0.,0.],[0.,4.,0.],[0.,0.,2.]])
L = np.array([[0.,0.,0.],[-2.,0.,0.],[0.,1.,0.]])
U = np.array([[0.,-2.,0.],[0.,0.,-1.],[0.,0.,0.]])
B_J = -np.dot(np.linalg.inv(D),(L+U))
print(B_J)
B_J_1 = np.linalg.norm(B_J, ord=1)
print("The 1-norm is: ",B_J_1)
B_J_2 = np.linalg.norm(B_J, ord=2)
print("The 2-norm is: ",B_J_2)
B_J_inf = np.linalg.norm(B_J, ord=np.inf)
print("The inf-norm is: ",B_J_inf)
print(np.abs(np.linalg.eigvals(B_J)))
x = jacobi(A, b, x0, 1)
print(x)

[[-0.          0.66666667 -0.        ]
 [ 0.5        -0.          0.25      ]
 [-0.         -0.5        -0.        ]]
The 1-norm is:  1.1666666666666665
The 2-norm is:  0.8333333333333333
The inf-norm is:  0.75
[0.45643546 0.45643546 0.        ]
0.8539125638299665
[ 1.    1.25 -1.5 ]


### **Code and Example to run the Gauss-Seidel Method**

In [6]:
# Gauss-Seidel method
def Gauss_Seidel(A, b, x_0, k):
    """
    Run k steps of Gauss_Seidel method
    A: the matrix
    b: the right-hand-side
    x_0: initial guess x0
    k: the number of steps
    """
    # Get the size of the system
    n = A.shape[0]
    # Initialize the solution vector
    x = x_0.copy()

    for l in range(k):
        for i in range(n):
            sum = 0.
            for j in range(n):
                if i != j:
                    sum += A[i,j]*x[j]
            x[i] = (b[i]-sum)/A[i,i]
        print(np.linalg.norm(b-np.dot(A,x))/np.linalg.norm(b))
    return x

In [7]:
# output for GS
A = np.array([[3.,-2,0],[-2,4,-1],[0,1,2]],dtype=float)
b = np.array([1,2.,-2])
x0 = np.array([1.,1.,1.])
#compute and print out the 1,2, and infinity norm of B_GS
D = np.array([[3.,0.,0.],[0.,4.,0.],[0.,0.,2.]])
L = np.array([[0.,0.,0.],[-2.,0.,0.],[0.,1.,0.]])
U = np.array([[0.,-2.,0.],[0.,0.,-1.],[0.,0.,0.]])
#-((D+L)^-1)*U
inv = np.linalg.inv(D+L)
print(inv)
B_GS = -np.dot(np.linalg.inv(D+L),U)
print(B_GS)
B_GS_1 = np.linalg.norm(B_GS, ord=1)
print("The 1-norm is: ",B_GS_1)
B_GS_2 = np.linalg.norm(B_GS, ord=2)
print("The 2-norm is: ",B_GS_2)
B_GS_inf = np.linalg.norm(B_GS, ord=np.inf)
print("The inf-norm is: ",B_GS_inf)
print(np.abs(np.linalg.eigvals(B_GS)))
x = Gauss_Seidel(A, b, x0, 1)
print(x)

[[ 0.33333333  0.          0.        ]
 [ 0.16666667  0.25        0.        ]
 [-0.08333333 -0.125       0.5       ]]
[[-0.          0.66666667 -0.        ]
 [-0.          0.33333333  0.25      ]
 [-0.         -0.16666667 -0.125     ]]
The 1-norm is:  1.1666666666666667
The 2-norm is:  0.7771538984844024
The inf-norm is:  0.6666666666666666
[0.         0.20833333 0.        ]
0.8907315969346645
[ 1.     1.25  -1.625]


### **Code and Example to run SOR Method**

In [ ]:
# SOR method
def SOR(A, b, x_0, omega, k):
    """
    Run k steps of the SOR method
    A: the matrix
    b: the right-hand-side
    x_0: initial guess x0
    omega: the relaxation parameter
    k: the number of steps
    """
    # Get the size of the system
    n = A.shape[0]
    # Initialize the solution vector
    x = x_0.copy()

    for l in range(k):
        for i in range(n):
            sum = 0.
            for j in range(n):
                if i != j:
                    sum += A[i,j]*x[j]
            x[i] = omega*(b[i]-sum)/A[i,i] + (1.-omega)*x[i]
    return x

In [ ]:
# output for SOR
A = np.array([[1.,1.,1.], [1., 2.,1.],[1.,1.,3.]])
b = np.array([-1., 5.,7.])
x0 = np.array([0.,0.,0.])

x = SOR(A, b, x0, 1.1, 100)
print(x)

[-11.   6.   4.]


### **Code and Example to compute optimal $\omega.$**

In [ ]:
#The spectral radius of B_SOR is the eigenvalue of B_SOR with
#maximum magnitude,and we want to choose ω so that |ρ (B_SOR (ω))| is a minimum
import numpy as np
from scipy.linalg import eig
def spectral_radius(A):
    D = np.diag(np.diag(A))
    L = -np.tril(A, k=-1)
    U = -np.triu(A, k=1)
    B = np.linalg.inv(D) @ (L + U)
    eigenvalues = eig(B)[0]
    return np.max(np.abs(eigenvalues))

def optimal_omega(A):
  rho_B = spectral_radius(A)
  return 2 / (1 + np.sqrt(1 - rho_B**2))


In [ ]:
# output for SOR with optimal Omega
A = np.array([[6.,-1.,2.,1.], [1., 6.,1.,-1.],[0.,1.,3.,1.],[1.,-2.,1.,5.]])
b = np.array([3., 2.,-6.,1.])
x0 = np.array([0.,0.,0.,0.])

omega_opt = optimal_omega(A)
print("Optimal omega:", omega_opt)

x = SOR(A, b, x0, omega_opt, 100)
print(x)

Optimal omega: 1.028249309849355
[ 1.30542986  0.63574661 -2.43891403  0.68099548]
