### **Code block #1:**
Code you implement to use the Python function for solving the system $Ax = b$.

In [14]:
import scipy.linalg
import numpy as np
#create the matrix with the given elements
A= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
b = np.array([1,0,2])
#Ax = b
x = scipy.linalg.solve(A,b)#solve for U^n+1_i
print(x)

[-2.          2.         -0.33333333]


### **Code Block #2:**
Code you can use to verify steps of LU decomposition.

In [15]:
import scipy.linalg
import numpy as np
#create the L1 matrix
L1 = np.array([[1, 0, 0], [-4, 1, 0], [0, 0, 1]])
#compute the L1 inverse
L1_inverse = scipy.linalg.inv(L1)
print(L1_inverse)
#create the L2 matrix
L2 = np.array([[1, 0, 0], [0, 1, 0], [-7, 0, 1]])
#compute L2 inverse
L2_inverse = scipy.linalg.inv(L2)
print(L2_inverse)
#create the L3 matrix
L3 = np.array([[1, 0, 0], [0, 1, 0], [0, -2, 1]])
#compute L3 inverse
L3_inverse = scipy.linalg.inv(L3)#solve for U^n+1_i
print(L3_inverse)
#
L2_inverse_X_L3_inverse = np.dot(L2_inverse,L3_inverse)
L1_inverse_X_L2_inverse_X_L3_inverse = np.dot(L1_inverse,L2_inverse_X_L3_inverse)
#verify that we get a Lower Triangular matrix
print("The matrix product is",L1_inverse_X_L2_inverse_X_L3_inverse)

[[ 1.  0. -0.]
 [ 4.  1. -0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 7.  0.  1.]]
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0.  2.  1.]]
The matrix product is [[1. 0. 0.]
 [4. 1. 0.]
 [7. 2. 1.]]


### **Code Block #3:**

Demonstration of what can go wrong!

Consider the matrix
$A = \begin{bmatrix}
10^{-20} & 1 \\
1 & 2\\
\end{bmatrix}$

What is $L_1$?

In [18]:
import scipy.linalg
import numpy as np
#create the matrix with the given elements
A = np.array([[10**(-20),1], [1, 2]])
L1 = np.array([[1,0], [-1/(10**(-20)),1]])
U = np.dot(L1,A)
#print("U = ",U)
L1_inverse = np.array([[1,0], [1/(10**(-20)),1]])
print("L1 inverse = ",L1_inverse)
print(f"A = {A} ?=? {np.dot(L1_inverse,U)} = LU")


L1 inverse =  [[1.e+00 0.e+00]
 [1.e+20 1.e+00]]
A = [[1.e-20 1.e+00]
 [1.e+00 2.e+00]] ?=? [[1.e-20 1.e+00]
 [1.e+00 0.e+00]] = LU


### **Code Block #4:**

And how to fix it!

In [4]:
import scipy.linalg
import numpy as np
#create the matrix with the given elements
A = np.array([[1,1],[10**(-20),1]])
L1 = np.array([[1, 0], [10**(-20),1]])
U = np.dot(L1,A)
print("U = ",U)
L1_inverse = np.array([[1, 0], [-10**(-20),1]])
print("L1 inverse = ",L1_inverse)
print(f"A = {A} ?=? {np.dot(L1_inverse,U)} = LU")

U =  [[1.e+00 1.e+00]
 [2.e-20 1.e+00]]
L1 inverse =  [[ 1.e+00  0.e+00]
 [-1.e-20  1.e+00]]
A = [[1.e+00 1.e+00]
 [1.e-20 1.e+00]] ?=? [[1.e+00 1.e+00]
 [1.e-20 1.e+00]] = LU
