$A = R^TR$ where R is upper triangular

$A = LL^T$ where L is lower triangular

In [5]:
import numpy as np
A = np.array([[1,2,6],[2,5,15],[6,15,46]])
L = np.linalg.cholesky(A)
print("L = ",L)

L =  [[1. 0. 0.]
 [2. 1. 0.]
 [6. 3. 1.]]


In [ ]:
print(np.dot(L,L.T))

[[1. 1. 1. 1.]
 [1. 2. 1. 2.]
 [1. 1. 3. 1.]
 [1. 2. 1. 4.]]


In [ ]:
# prompt: write code to do a cholesky facotrization

import numpy as np

# Example usage with a different matrix (ensure positive definiteness)
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
L = np.linalg.cholesky(A)
print(L)


[[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]
